# Generated by Django 3.1.4 on 2020-12-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20201218_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('overview', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=800)),
                ('body', models.CharField(max_length=8000)),
                ('pub_date', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'name',
                'verbose_name_plural': 'names',
                'ordering': ['id'],
            },
        ),
    ]
