# Generated by Django 3.1.4 on 2020-12-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='name',
            new_name='overview',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='ur_local',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='time',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='week',
        ),
        migrations.AddField(
            model_name='courses',
            name='badge_url',
            field=models.URLField(default=0, max_length=800),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='created_at',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='title',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
