# Generated by Django 3.1.4 on 2020-12-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auto_20201219_1804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'ordering': ['id'], 'verbose_name': 'infomation', 'verbose_name_plural': 'informations'},
        ),
        migrations.AlterModelOptions(
            name='milestone',
            options={'ordering': ['id'], 'verbose_name': 'milestone', 'verbose_name_plural': 'mileestones'},
        ),
        migrations.AlterField(
            model_name='courses',
            name='badge_url',
            field=models.URLField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='created_at',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='overview',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='url',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='overview',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='pub_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='url',
            field=models.URLField(max_length=800, null=True),
        ),
    ]
