# Generated by Django 3.1.4 on 2020-12-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_auto_20201219_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='image_url',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
