# Generated by Django 3.1.4 on 2020-12-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_info_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studen',
            old_name='name',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='studen',
            name='photo',
        ),
        migrations.AddField(
            model_name='studen',
            name='progress',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studen',
            name='user',
            field=models.CharField(default=0, max_length=80),
            preserve_default=False,
        ),
    ]
